package com.example.sales.controllers;
import com.example.sales.models.OrderItem;
import com.example.sales.repositories.OrderItemRepository;
import com.example.sales.repositories.SalesOrderRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;

@Controller // This means that this class is a Controller
public class OrderItemController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private OrderItemRepository orderItemRepository;
}